<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <GenerateDocumentationFile Condition=" '$(Configuration)' == 'Release' ">true</GenerateDocumentationFile>
    <VersionSuffix></VersionSuffix>
    <VersionPrefix>3.0.0</VersionPrefix>
    <FileVersion>3.0.0.0</FileVersion>
    <Product>Camunda REST API Client</Product>
    <Title>Camunda REST API Client</Title>
    <Authors>Jan Lucansky</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/jlucansky/Camunda.Api.Client</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <Description>Camunda REST API Client for .NET platform</Description>
    <PackageTags>camunda rest refit bpmn bpm</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
    <RepositoryType></RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <NoWarn>1701;1702;1705;1591;8002</NoWarn>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <!-- Don't increment AssemblyVersion -->
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\Key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Refit" Version="16.3.0" />
    <PackageReference Include="Refit.Newtonsoft.Json" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <!-- wait for manually signing to complete -->
    <Exec Condition="$(SIGNTOOL_WAIT) != ''" Command="start cmd /c pause" />
  </Target>

</Project>
